name: Renovate Dependencies

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'info'
        type: choice
        options:
          - debug
          - info
          - warn
          - error
      dryRun:
        description: 'Dry run (no changes made)'
        required: false
        type: boolean
        default: false

  # Scheduled trigger - every weekday at 6 AM CET
  schedule:
    - cron: '0 5 * * 1-5'  # 5 AM UTC = 6 AM CET (winter), 4 AM UTC = 6 AM CEST (summer)

env:
  LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
  DRY_RUN: ${{ inputs.dryRun || false }}

permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: write

jobs:
  renovate:
    name: Renovate Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch full history for better renovate performance
          fetch-depth: 0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.8
        with:
          configurationFile: renovate.json
          token: ${{ secrets.BOT_PAT }}
        env:
          # Optional: Configure additional settings
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_USERNAME: renovate[bot]
          RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'
          LOG_LEVEL: ${{ env.LOG_LEVEL }}
          RENOVATE_DRY_RUN: ${{ env.DRY_RUN }}
          RENOVATE_REQUIRE_CONFIG: 'required'

      - name: Renovate summary
        if: always()
        run: |
          echo "## Renovate Run Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Log Level**: ${{ env.LOG_LEVEL }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Dry Run**: ${{ env.DRY_RUN }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Repository**: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Triggered by**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "- **Triggered by user**: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          fi